on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🐛 Debug EXPO_TOKEN
        run: if [ -z "$EXPO_TOKEN" ]; then echo "EXPO_TOKEN is not set"; else echo "EXPO_TOKEN is set"; fi

      - name: 🐛 Check EAS CLI version
        run: eas --version

      - name: 🚀 Publish app
        run: eas update --branch main --message main --non-interactive
